return [
  {
    id: 1,
    visit_type: 'Doctor',
    doctor_name: 'Dr. Emily Smith',
    specialty: 'Cardiologist',
    diagnosis: 'Hypertension',
    prescription: 'Prescribed blood pressure medication.',
    price: '$150',
    date_time: '2023-09-05 10:30 AM',
  },
  {
    id: 2,
    visit_type: 'Procedure',
    procedure_name: 'X-ray',
    price: '$200',
    date_time: '2023-08-28 09:15 AM',
  },
  {
    id: 3,
    visit_type: 'Test',
    test_name: 'Blood Glucose Test',
    results: {
      glucose_level: '130 mg/dL',
      hemoglobin_A1c: '6.2%',
    },
    is_ok: true,
    price: '$50',
    date_time: '2023-08-22 11:00 AM',
  },
  {
    id: 4,
    visit_type: 'Test',
    test_name: 'Kidney Function Test',
    results: {
      creatinine_level: '0.9 mg/dL',
      bun_level: '12 mg/dL',
      egfr: '85 mL/min',
    },
    is_ok: false,
    price: '$70',
    date_time: '2023-05-10 09:15 AM',
  },
  {
    id: 5,
    visit_type: 'Doctor',
    doctor_name: 'Dr. David Brown',
    specialty: 'Neurologist',
    diagnosis: 'Migraine',
    prescription: 'Prescribed migraine medication.',
    price: '$95',
    date_time: '2023-04-28 03:20 PM',
  },
  {
    id: 6,
    visit_type: 'Procedure',
    procedure_name: 'Endoscopy',
    price: '$600',
    date_time: '2023-04-15 02:45 PM',
  },
  {
    id: 7,
    visit_type: 'Procedure',
    procedure_name: 'Colonoscopy',
    price: '$700',
    date_time: '2023-04-02 11:30 AM',
  },
  {
    id: 8,
    visit_type: 'Test',
    test_name: 'Thyroid Function Test',
    results: {
      tsh_level: '1.8 mIU/L',
      t3_level: '2.0 ng/dL',
      t4_level: '1.5 ng/dL',
    },
    is_ok: true,
    price: '$45',
    date_time: '2023-03-25 10:00 AM',
  },
  {
    visit_type: 'Doctor',
    doctor_name: 'Dr. Maria Garcia',
    specialty: 'Obstetrician-Gynecologist',
    diagnosis: 'Pregnancy Checkup',
    prescription: 'Provided prenatal vitamins.',
    price: '$120',
    date_time: '2023-03-15 03:15 PM',
  },
  {
    id: 9,
    visit_type: 'Procedure',
    procedure_name: 'Echocardiogram',
    price: '$350',
    date_time: '2023-03-08 08:45 AM',
  },
  {
    id: 10,
    visit_type: 'Test',
    test_name: 'Lipid Panel',
    results: {
      total_cholesterol: '180 mg/dL',
      hdl_cholesterol: '55 mg/dL',
      ldl_cholesterol: '115 mg/dL',
    },
    is_ok: false,
    price: '$55',
    date_time: '2023-02-28 09:30 AM',
  },
  {
    id: 11,
    visit_type: 'Doctor',
    doctor_name: 'Dr. Richard Wilson',
    specialty: 'Urologist',
    diagnosis: 'Urinary Tract Infection',
    prescription: 'Prescribed antibiotics.',
    price: '$90',
    date_time: '2023-02-20 01:00 PM',
  },
  {
    id: 12,
    visit_type: 'Procedure',
    procedure_name: 'Bone Density Scan',
    price: '$250',
    date_time: '2023-02-12 10:30 AM',
  },
  {
    id: 13,
    visit_type: 'Test',
    test_name: 'Hepatitis B Test',
    results: {
      hbv_antibody: 'Positive',
      hbv_surface_antigen: 'Negative',
    },
    is_ok: true,
    price: '$40',
    date_time: '2023-01-28 11:45 AM',
  },
  {
    id: 14,
    visit_type: 'Doctor',
    doctor_name: 'Dr. Patricia Miller',
    specialty: 'Psychiatrist',
    diagnosis: 'Depression',
    prescription: 'Prescribed antidepressant medication.',
    price: '$110',
    date_time: '2023-01-20 03:30 PM',
  },
  {
    id: 15,
    visit_type: 'Procedure',
    procedure_name: 'Ultrasound',
    price: '$180',
    date_time: '2023-01-15 09:15 AM',
  },
];